@PE_PRN231_SP25_TrialTest_SE170255_BE.APIService_HostAddress = https://localhost:5050

GET {{PE_PRN231_SP25_TrialTest_SE170255_BE.APIService_HostAddress}}/api/CosmeticInformation?filter=CosmeticName%20eq%20%27CeraVe%20Hydrating%20Facial%20Cleanser%27
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBDb3NtZXRpY3NEQi5pbmZvIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiMSIsImV4cCI6MTc0MjQxNjEzMiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI1NCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNTQifQ.XYu_flhoadRA-DXWgzM1qaenVvLyQuxoCv0_x-oNdyU
###
