//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaccinaCareWCFReferences
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HealthGuide", Namespace="http://schemas.datacontract.org/2004/07/VaccinaCare.SoapAPIServices.PHUCTG.SoapMod" +
        "els")]
    public partial class HealthGuide : object
    {
        
        private string AuthorField;
        
        private string ContentField;
        
        private System.DateTime CreatedAtField;
        
        private VaccinaCareWCFReferences.HealthGuideCategory HealthGuideCategorieField;
        
        private System.Nullable<int> HealthGuideCategorieIdField;
        
        private int IdField;
        
        private string ImageUrlField;
        
        private bool IsActiveField;
        
        private string TitleField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private int ViewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VaccinaCareWCFReferences.HealthGuideCategory HealthGuideCategorie
        {
            get
            {
                return this.HealthGuideCategorieField;
            }
            set
            {
                this.HealthGuideCategorieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HealthGuideCategorieId
        {
            get
            {
                return this.HealthGuideCategorieIdField;
            }
            set
            {
                this.HealthGuideCategorieIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl
        {
            get
            {
                return this.ImageUrlField;
            }
            set
            {
                this.ImageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Views
        {
            get
            {
                return this.ViewsField;
            }
            set
            {
                this.ViewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HealthGuideCategory", Namespace="http://schemas.datacontract.org/2004/07/VaccinaCare.SoapAPIServices.PHUCTG.SoapMod" +
        "els")]
    public partial class HealthGuideCategory : object
    {
        
        private string DescriptionField;
        
        private VaccinaCareWCFReferences.HealthGuide[] HealthGuidesField;
        
        private int IdField;
        
        private bool IsActiveField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VaccinaCareWCFReferences.HealthGuide[] HealthGuides
        {
            get
            {
                return this.HealthGuidesField;
            }
            set
            {
                this.HealthGuidesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VaccinaCareWCFReferences.IHealthGuideSoapService")]
    public interface IHealthGuideSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHealthGuideSoapService/GetAll", ReplyAction="http://tempuri.org/IHealthGuideSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<VaccinaCareWCFReferences.HealthGuide[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHealthGuideSoapService/GetById", ReplyAction="http://tempuri.org/IHealthGuideSoapService/GetByIdResponse")]
        System.Threading.Tasks.Task<VaccinaCareWCFReferences.HealthGuide> GetByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IHealthGuideSoapServiceChannel : VaccinaCareWCFReferences.IHealthGuideSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class HealthGuideSoapServiceClient : System.ServiceModel.ClientBase<VaccinaCareWCFReferences.IHealthGuideSoapService>, VaccinaCareWCFReferences.IHealthGuideSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HealthGuideSoapServiceClient() : 
                base(HealthGuideSoapServiceClient.GetDefaultBinding(), HealthGuideSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHealthGuideSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthGuideSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HealthGuideSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), HealthGuideSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthGuideSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HealthGuideSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthGuideSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HealthGuideSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HealthGuideSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VaccinaCareWCFReferences.HealthGuide[]> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<VaccinaCareWCFReferences.HealthGuide> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHealthGuideSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHealthGuideSoapService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5092/healthGuideService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HealthGuideSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHealthGuideSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HealthGuideSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHealthGuideSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IHealthGuideSoapService,
        }
    }
}
